### ISSUE TITLE
Stand-up meeting May-27

### ISSUE THREAD

**Issue by mariordgez** [ad9311/rtomlcop#1]
Great progress so far, you have already a lot of working cases for the linters, keep progressing and debugging your code and you should be great.

**Comment by DanSam5K** [comment]
Seems to be doing pretty good with the project excellent work so far!💡🎉

**Comment by YuvrajM108** [comment]
Great job so far. Keep focusing on making sure that it accounts for the basic syntax errors and then if you have more time you can work on making it account for other errors.
